language: bash

matrix:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - opam
    - os: osx
      osx_image: xcode12.2
      addons:
        homebrew:
          packages:
            - opam

git:
  depth: 5
  submodules: false

before_install:
  - export -f travis_nanoseconds travis_time_start travis_time_finish

script:
  - ./script/travis.sh
